services:
  haproxy:
    image: haproxytech/haproxy-alpine
    container_name: haproxy_server
    volumes:
      - /home/pavel/VSCODE/ccsa2324/practica1esc2:/usr/local/etc/haproxy:ro
    restart: always
    ports:
      - 80:80
      - 8404:8404
    depends_on:
      - web

  web:
    image: jmalloc/echo-server
    restart: always
    ports:
      - "8080-8082:8080"
    deploy:
      replicas: 3
      mode: vip
  
